// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Modules/ModuleManager.h"

/** IModuleInterface implementation generated by ue4 */
class FPolygonMasksGeneratorModule : public IModuleInterface
{
public:

	/** @name Implementation of IModuleInterface*/
	///@{
	virtual void StartupModule() override;	
	virtual void ShutdownModule() override;
	///@}
};
