// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Modules/ModuleManager.h"

/** IModuleInterface implementation generated by ue4 */
class FGeoTempCoreModule : public IModuleInterface
{
public:

    /** IModuleInterface implementation */
    virtual void StartupModule() override;
    /** IModuleInterface implementation */
    virtual void ShutdownModule() override;
};
